let p = Promise.resolve(new Error("NÃ£o Deu Certo."));

console.log("AINDA!")
.catch(reason => console.log("Falhou " + reason))

p.then(value => console.log(value))